import type {
  ArrangementResponse,
  CapabilitiesResponse,
  DifficultyCheckResponse,
} from "../src/types";

export const publishedGrade: DifficultyCheckResponse["published_grade"] = {
  model_version: "published-grade-estimator@0.1.0",
  model_sha256: "a3bb39aaf5f881513ed0141d20b3e3776c8b38357dd11351681c38701dddf16a",
  grade_system: "Delcamp/Eric Crouch 1–10",
  estimated_grade: 5,
  likely_interval: { lower: 4, upper: 6 },
  band: "foundational",
  confidence: "low",
  burden_percentile: 32.4,
  feature_percentiles: { midi_max: 30.1, max_chord_stack: 34.7 },
  training_scope: "427 attributed classical-guitar scores; one curator; composer-confounded",
  meaning: "corpus_calibrated_estimate_not_a_playability_guarantee",
};

export const capabilities: CapabilitiesResponse = {
  api_version: "fretsure-api@0.3.0",
  package_version: "0.6.0",
  service_version: "fretsure-service@0.3.0",
  trace_schema_version: "agent-trace@0.3.0",
  profile_registry_version: "profile-registry@0.2.0",
  engines: [
    { id: "offline", available: true, model_id: "constant-stub" },
    { id: "proxy", available: true, model_id: "gpt-5.6-sol" },
  ],
  profiles: [
    {
      name: "small",
      version: "small@0.2",
      fingerprint: "small123",
      calibration_status: "placeholder_pending_human_calibration",
    },
    {
      name: "median",
      version: "median@0.2",
      fingerprint: "abc123",
      calibration_status: "placeholder_pending_human_calibration",
    },
    {
      name: "large",
      version: "large@0.1",
      fingerprint: "large123",
      calibration_status: "placeholder_pending_human_calibration",
    },
  ],
  arrangement_styles: [
    { id: "fingerstyle", label: "Fingerstyle", description: "Balanced solo texture." },
    { id: "classical", label: "Classical", description: "Measured voice leading." },
    { id: "jazz", label: "Jazz", description: "Shell colors and syncopation." },
    { id: "rnb", label: "R&B", description: "Spacious pocket." },
  ],
  technique_profiles: [
    { id: "balanced", label: "Balanced", description: "General ergonomic ordering." },
    { id: "avoid_barres", label: "Avoid barres", description: "Less barre burden." },
    { id: "low_position", label: "Low position", description: "Prefer lower frets." },
    { id: "minimize_shifts", label: "Fewer shifts", description: "Reduce position changes." },
  ],
  difficulty_tiers: [
    {
      name: "beginner",
      profile: {
        name: "beginner",
        version: "beginner@0.1",
        fingerprint: "beginner-fingerprint",
        calibration_status: "placeholder_pending_human_calibration",
      },
      constraints: {
        max_simultaneous: 2,
        allow_barre: false,
        max_position: 5,
        max_shifts_per_bar: 2,
      },
    },
    {
      name: "intermediate",
      profile: {
        name: "intermediate",
        version: "intermediate@0.1",
        fingerprint: "intermediate-fingerprint",
        calibration_status: "placeholder_pending_human_calibration",
      },
      constraints: {
        max_simultaneous: 3,
        allow_barre: true,
        max_position: 9,
        max_shifts_per_bar: 4,
      },
    },
    {
      name: "advanced",
      profile: {
        name: "advanced",
        version: "advanced@0.1",
        fingerprint: "advanced-fingerprint",
        calibration_status: "placeholder_pending_human_calibration",
      },
      constraints: {
        max_simultaneous: 4,
        allow_barre: true,
        max_position: 19,
        max_shifts_per_bar: 99,
      },
    },
  ],
  inputs: {
    score_suffixes: [".musicxml", ".xml", ".mxl", ".mid", ".midi"],
    score_input: {
      router_version: "score-input@0.1.0",
      format_importers: {
        musicxml: "musicxml@0.4.0",
        mxl: "musicxml@0.4.0",
        midi: "midi@0.1.0",
      },
    },
    max_xml_bytes: 10 * 1024 * 1024,
    max_mxl_bytes: 20 * 1024 * 1024,
  },
  controls: {
    arrange: {
      defaults: {
        profile: "median",
        style: "fingerstyle",
        difficulty_tier: "intermediate",
        technique_profile: "balanced",
        n: 1,
        max_iters: 0,
        use_critic: false,
        tempo_bpm: null,
        engine: "offline",
      },
      n: { min: 1, max: 8 },
      max_iters: { min: 0, max: 16 },
      tempo_bpm: { min: 1, max: 1000, nullable: true },
    },
    difficulty: {
      defaults: { tier: "beginner", tempo_bpm: 90, beats_per_bar: 4 },
      tier: { values: ["beginner", "intermediate", "advanced"] },
      tempo_bpm: { min: 1, max: 1000 },
      beats_per_bar: { min: 1, max: 128 },
    },
  },
  implemented: ["arrange_score_bytes", "render_audio"],
  deferred: [],
  audio: {
    available: true,
    renderer: "FluidSynth",
    runtime_version: "2.5.6",
    export_version: "tab-audio@0.1.0",
    sample_rate_hz: 44100,
    media_type: "audio/wav",
  },
  stamps: {
    package_version: "0.6.0",
    service_version: "fretsure-service@0.3.0",
    profile_registry_version: "profile-registry@0.2.0",
    arrangement_style_registry_version: "arrangement-style-registry@0.2.0",
    arrangement_style_profile_version: "guitarset-style-profiles@0.1.0",
    arrangement_style_profile_sha256:
      "c1a57bb1aa4599594db83f5fb9074e96b53be83a03d1e306e38ea5cae7df342d",
    technique_profile_registry_version: "technique-profile-registry@0.1.0",
    score_input_version: "score-input@0.1.0",
    oracle_checker_version: "oracle@0.7.0",
    fidelity_checker_version: "fidelity@0.3.0",
    difficulty_checker_version: "difficulty@0.1.0",
    fingering_solver_version: "fingering-solver@0.7.0",
    score_solver_version: "score-solver@0.4.0",
    left_hand_model_version: "left-hand-ergonomics@0.1.0",
    published_fingering_ranker_version: "published-fingering-ranker@0.1.0",
    published_fingering_model_sha256:
      "10bd1f9c2751417c5ef3a5f360da5696f736cc24db838857b9d2dd058b6cfed0",
    published_fingering_feature_schema: "published-fingering-features@0.1.0",
    editable_target_schema_version: "editable-arrangement-target@0.1.0",
    section_regeneration_version: "section-regeneration@0.1.0",
    trace_schema_version: "agent-trace@0.3.0",
  },
};

export const arrangement: ArrangementResponse = {
  api_version: "fretsure-api@0.3.0",
  service_version: "fretsure-service@0.3.0",
  status: "tab_produced",
  source: {
    filename: "example.musicxml",
    format: "musicxml",
    raw_sha256: "a".repeat(64),
    root_member: null,
    root_sha256: "a".repeat(64),
    container_version: null,
    importer_version: "musicxml@0.4.0",
    warnings: [],
  },
  score: {
    title: "Evidence Song",
    key: "C major",
    time_signature: { numerator: 4, denominator: 4 },
    source_tempo_bpm: 90,
    duration_beats: "4/1",
    note_count: 4,
    voice_counts: { melody: 2, bass: 2, harmony: 0 },
    chord_count: 1,
    source_description: "fixture",
    rights_or_license: "CC0",
  },
  options: {
    profile: capabilities.profiles[1],
    style: "fingerstyle",
    difficulty_tier: "intermediate",
    technique_profile: "balanced",
    tuning: [40, 45, 50, 55, 59, 64],
    capo: 0,
    candidate_count: 1,
    max_repair_iterations: 0,
    critic_enabled: false,
    tempo_override_bpm: null,
    source_tempo_bpm: 90,
    effective_tempo_bpm: 90,
  },
  model: { model_id: "constant-stub", engine: "offline" },
  editable_target: {
    schema_version: "editable-arrangement-target@0.1.0",
    notes: [{ onset: "0/1", duration: "1/1", pitch: 60, voice: "melody" }],
  },
  tab: { tuning: [40, 45, 50, 55, 59, 64], capo: 0, notes: [] },
  ascii: "e|--0--|\nB|--1--|\nG|--0--|\nD|--2--|\nA|--3--|\nE|-----|",
  playability: {
    verdict: "GREEN",
    meaning: "versioned_model_relative_not_a_real_player_guarantee",
    diagnostics: [],
    checker_version: "oracle@0.7.0",
    profile_version: "median@0.2",
    profile_fingerprint: "abc123",
    input_schema_version: "tab-input@0.3.0",
  },
  faithfulness: {
    melody_f1: 1,
    bass_root_accuracy: 0.75,
    harmony_jaccard: 0.75,
    evaluated_dimensions: ["melody", "bass_root", "harmony"],
    unavailable_dimensions: [],
    passed: true,
    checker_version: "fidelity@0.3.0",
  },
  alternatives: [],
  trace: {
    schema_version: "agent-trace@0.3.0",
    steps: [
      {
        trace_schema_version: "agent-trace@0.3.0",
        seq: 0,
        kind: "PLAN",
        event: "PIPELINE_CONFIGURED",
        candidate_index: null,
        iteration: null,
        detail: "Configured a bounded pipeline.",
        data: { checker_version: "oracle@0.7.0" },
      },
      {
        trace_schema_version: "agent-trace@0.3.0",
        seq: 1,
        kind: "ORACLE",
        event: "PLAYABILITY_CHECKED",
        candidate_index: 0,
        iteration: 0,
        detail: "Oracle returned GREEN with 0 diagnostics.",
        data: { verdict: "GREEN" },
      },
      {
        trace_schema_version: "agent-trace@0.3.0",
        seq: 2,
        kind: "SELECT",
        event: "CANDIDATE_SELECTED",
        candidate_index: 0,
        iteration: null,
        detail: "Selected the highest-ranked verified candidate.",
        data: {
          winner_candidate_index: 0,
          candidates_considered: 1,
          verdict: "GREEN",
          green_certified: true,
          playability_gate: "passed",
          faithfulness_passed: true,
          ranking_melody_recall: 1,
          ranking_bass_preserved: 1,
          ranking_harmony_jaccard: 0.75,
          melody_f1: 1,
          bass_root_accuracy: 0.75,
          harmony_jaccard: 0.75,
          evaluated_dimensions: ["melody", "bass_root", "harmony"],
          unavailable_dimensions: [],
          critic_status: "NOT_RUN",
          critic_overall: null,
        },
      },
    ],
  },
  stamps: {
    package_version: "0.6.0",
    service_version: "fretsure-service@0.3.0",
    score_input_version: "score-input@0.1.0",
    profile_registry_version: "profile-registry@0.2.0",
    arrangement_style_registry_version: "arrangement-style-registry@0.2.0",
    arrangement_style_profile_version: "guitarset-style-profiles@0.1.0",
    arrangement_style_profile_sha256:
      "c1a57bb1aa4599594db83f5fb9074e96b53be83a03d1e306e38ea5cae7df342d",
    technique_profile_registry_version: "technique-profile-registry@0.1.0",
    profile_version: "median@0.2",
    profile_fingerprint: "abc123",
    oracle_checker_version: "oracle@0.7.0",
    oracle_input_schema_version: "tab-input@0.3.0",
    fidelity_checker_version: "fidelity@0.3.0",
    fingering_solver_version: "fingering-solver@0.7.0",
    score_solver_version: "score-solver@0.4.0",
    left_hand_model_version: "left-hand-ergonomics@0.1.0",
    published_fingering_ranker_version: "published-fingering-ranker@0.1.0",
    published_fingering_model_sha256:
      "10bd1f9c2751417c5ef3a5f360da5696f736cc24db838857b9d2dd058b6cfed0",
    published_fingering_feature_schema: "published-fingering-features@0.1.0",
    target_input_schema_version: "target-input@0.1.0",
    editable_target_schema_version: "editable-arrangement-target@0.1.0",
    section_regeneration_version: "section-regeneration@0.1.0",
    trace_schema_version: "agent-trace@0.3.0",
    importer_version: "musicxml@0.4.0",
    model_id: "constant-stub",
  },
};

const unprovidedKey = "key-signature:fifths=0;mode=unprovided";
const keyModeUnprovidedWarning = {
  code: "KEY_MODE_UNPROVIDED",
  severity: "warning" as const,
  message: "traditional key signature supplied no mode; no mode was inferred",
  location: {
    part_id: "P1",
    measure: "1",
    voice: null,
    element: "key",
    archive_member: null,
    track_index: null,
    event_index: null,
    channel: null,
    tick: null,
  },
};

export const producerXmlArrangement: ArrangementResponse = {
  ...arrangement,
  source: {
    filename: "musescore-4.7.4.musicxml",
    format: "musicxml",
    raw_sha256: "8aa3f622429dee2dda26ca91c87237470d60c4c02fb996bd9171c9238cd77386",
    root_member: null,
    root_sha256: "8aa3f622429dee2dda26ca91c87237470d60c4c02fb996bd9171c9238cd77386",
    container_version: null,
    importer_version: "musicxml@0.4.0",
    warnings: [keyModeUnprovidedWarning],
  },
  score: {
    title: "Fretsure Producer Etude",
    key: unprovidedKey,
    time_signature: { numerator: 4, denominator: 4 },
    source_tempo_bpm: 96,
    duration_beats: "4/1",
    note_count: 4,
    voice_counts: { melody: 4, bass: 0, harmony: 0 },
    chord_count: 1,
    source_description:
      "filename=musescore-4.7.4.musicxml;format=musicxml;sha256=8aa3f622429dee2dda26ca91c87237470d60c4c02fb996bd9171c9238cd77386;root_sha256=8aa3f622429dee2dda26ca91c87237470d60c4c02fb996bd9171c9238cd77386;importer=musicxml@0.4.0",
    rights_or_license: "CC0-1.0",
  },
  options: {
    ...arrangement.options,
    candidate_count: 1,
    max_repair_iterations: 0,
    critic_enabled: false,
    source_tempo_bpm: 96,
    effective_tempo_bpm: 96,
  },
};

export const producerMxlArrangement: ArrangementResponse = {
  ...arrangement,
  source: {
    filename: "musescore-4.7.4-roundtrip-supported_basic.mxl",
    format: "mxl",
    raw_sha256: "9fbca0cd86c4110a24a51c46a7982859a3d39e1cadfb50d5ad31a479fafe0cc1",
    root_member: "score.xml",
    root_sha256: "e6af1f610580baa3c6a588d738a7aeb690cfd19f684a1dbaa6cc1d91c681a39f",
    container_version: "mxl-container@0.1.0",
    importer_version: "musicxml@0.4.0",
    warnings: [
      {
        code: "MXL_ROOTFILE_MEDIA_TYPE_UNPROVIDED",
        severity: "warning",
        message: "container rootfile omits media-type; accepted by the extension/path contract",
        location: {
          part_id: null,
          measure: null,
          voice: null,
          element: "rootfile",
          archive_member: "META-INF/container.xml",
          track_index: null,
          event_index: null,
          channel: null,
          tick: null,
        },
      },
      keyModeUnprovidedWarning,
    ],
  },
  score: {
    title: "Importer Etude",
    key: unprovidedKey,
    time_signature: { numerator: 4, denominator: 4 },
    source_tempo_bpm: 96,
    duration_beats: "8/1",
    note_count: 4,
    voice_counts: { melody: 4, bass: 0, harmony: 0 },
    chord_count: 2,
    source_description:
      "filename=musescore-4.7.4-roundtrip-supported_basic.mxl;format=mxl;sha256=9fbca0cd86c4110a24a51c46a7982859a3d39e1cadfb50d5ad31a479fafe0cc1;root_sha256=e6af1f610580baa3c6a588d738a7aeb690cfd19f684a1dbaa6cc1d91c681a39f;root_member=score.xml;importer=musicxml@0.4.0;container=mxl-container@0.1.0",
    rights_or_license: "CC0-1.0",
  },
  options: {
    ...arrangement.options,
    candidate_count: 1,
    max_repair_iterations: 0,
    critic_enabled: false,
    source_tempo_bpm: 96,
    effective_tempo_bpm: 96,
  },
};

export const midiArrangement: ArrangementResponse = {
  ...arrangement,
  source: {
    filename: "melody.mid",
    format: "midi",
    raw_sha256: "b".repeat(64),
    root_member: null,
    root_sha256: "b".repeat(64),
    container_version: null,
    importer_version: "midi@0.1.0",
    warnings: [
      {
        code: "MIDI_HARMONY_UNPROVIDED",
        severity: "warning",
        message: "MIDI supplied no chord or harmony evidence",
        location: {
          part_id: null,
          measure: null,
          voice: null,
          element: null,
          archive_member: null,
          track_index: 0,
          event_index: 1,
          channel: 1,
          tick: 0,
        },
      },
    ],
  },
  score: {
    title: "MIDI Melody",
    key: "key-signature:unprovided",
    time_signature: { numerator: 4, denominator: 4 },
    source_tempo_bpm: 120,
    duration_beats: "4/1",
    note_count: 4,
    voice_counts: { melody: 4, bass: 0, harmony: 0 },
    chord_count: 0,
    source_description: "strict MIDI melody fixture",
    rights_or_license: "unprovided",
  },
  options: {
    ...arrangement.options,
    source_tempo_bpm: 120,
    effective_tempo_bpm: 120,
  },
  faithfulness: {
    melody_f1: 1,
    bass_root_accuracy: null,
    harmony_jaccard: null,
    evaluated_dimensions: ["melody"],
    unavailable_dimensions: ["bass_root", "harmony"],
    passed: true,
    checker_version: "fidelity@0.3.0",
  },
  trace: {
    schema_version: "agent-trace@0.3.0",
    steps: [
      ...arrangement.trace.steps.filter((step) => step.event !== "CANDIDATE_SELECTED"),
      {
        trace_schema_version: "agent-trace@0.3.0",
        seq: arrangement.trace.steps.length - 1,
        kind: "SELECT",
        event: "CANDIDATE_SELECTED",
        candidate_index: 0,
        iteration: null,
        detail: "Selected the highest-ranked verified candidate.",
        data: {
          winner_candidate_index: 0,
          candidates_considered: 1,
          verdict: "GREEN",
          green_certified: true,
          playability_gate: "passed",
          faithfulness_passed: true,
          ranking_melody_recall: 1,
          ranking_bass_preserved: 1,
          ranking_harmony_jaccard: 1,
          melody_f1: 1,
          bass_root_accuracy: null,
          harmony_jaccard: null,
          evaluated_dimensions: ["melody"],
          unavailable_dimensions: ["bass_root", "harmony"],
          critic_status: "NOT_RUN",
          critic_overall: null,
        },
      },
    ],
  },
  stamps: {
    ...arrangement.stamps,
    importer_version: "midi@0.1.0",
  },
};

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": status >= 400 ? "application/problem+json" : "application/json" },
  });
}
